### ISSUE TITLE
Cannot include jekyll-figure

### ISSUE THREAD

**Issue by wkirby** [paulrobertlloyd/jekyll-figure#1]
Adding `gems: [jekyll-figure]` to `_config.yml` doesn't work, have to add `gems: ["jekyll/figure"]`.

**Comment by kenman345** [comment]
in the `_config.yml` you actually need to use the `plugins:` keyword not `gems:` since v3.5.0

**Comment by kenman345** [comment]
But yes, the creator chose to nest the folder structure so the normal structure for the gem is not valid and you thus have to use the slash in the definition of what to use for the gem. Otherwise it does not find the .rb to use

**Comment by paulrobertlloyd** [comment]
Hi @wkirby. Sorry it’s taken me a while to address this issue. I have now merged @kenman345 changes.
