### ISSUE TITLE
cannot load such file -- jekyll-figure

### ISSUE THREAD

**Issue by justinechacko** [paulrobertlloyd/jekyll-figure#2]
`Dependency Error: Yikes! It looks like you don't have jekyll-figure or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-figure' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! `
I added gem to gemfile and did a bundle install ...Still got error message

**Comment by paulrobertlloyd** [comment]
Hi @justinechacko. Sorry it’s taken me a while to address this issue. I have now merged @kenman345 changes.
